site_name: AgriNode Project
pages:
- Home: index.md
- System Architecture: system_architech.md
- Install Kura on Orange Pi: orangepi.md
- Install Node-RED on Orange Pi: install_nodered_orangepi.md
- MQTT demo: mqtt_demo.md
- Bitreactive tutorial: Bitreactive_tutorial.md
- Node Red tutorial: nodered_tutorial.md
- OpenHAB: openhab2_weather_demo.md

theme: readthedocs